# Generated by Django 4.2.30 on 2026-09-25 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable office name', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Office GPS latitude', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Office GPS longitude', max_digits=9)),
                ('allowed_radius_meters', models.IntegerField(default=100, help_text='Maximum allowed distance in meters for valid attendance')),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_office_lat_lon')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Server-side timestamp of the attendance attempt')),
                ('latitude', models.DecimalField(decimal_places=6, help_text="User's GPS latitude", max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text="User's GPS longitude", max_digits=9)),
                ('distance_meters', models.FloatField(help_text='Calculated distance in meters from the office')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('REJECTED', 'Rejected')], help_text='Attendance result: PRESENT if within radius, else REJECTED', max_length=10)),
                ('user', models.ForeignKey(help_text='The user who attempted to mark attendance', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_log_lat_lon')],
            },
        ),
    ]
