# Generated by Django 4.2.30 on 2026-09-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='action_type',
            field=models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], default='CHECK_IN', help_text='Whether this was a check-in or check-out', max_length=10),
        ),
    ]
